x-environment: &environment
  MYSQL_HOST: db
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DB_DATA: traume
  FALK_APP_ID: 80
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":80,\"R\":\"LC\",\"U\":1},{\"A\":80,\"R\":\"SC\",\"U\":2},{\"A\":81,\"R\":\"LC\",\"U\":2}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"


services:
  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    platform: "linux/amd64"
    volumes:
      - ./dev/mysql:/docker-entrypoint-initdb.d

  app:
    image: rapporteket/traume:main
    ports:
      - 3838:3838
    environment:
      << : *environment
    platform: "linux/amd64"

  dev:
    depends_on:
      - db
    image: rapporteket/ltmv-dev:main
    volumes:
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/traume
    ports:
      - "8787:8787"
    restart: "no"
    platform: "linux/amd64"
    environment:
      << : *environment
      DISABLE_AUTH: "true"

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
    platform: "linux/amd64"
